services:
  postgres:
    image: postgres:latest
    container_name: fincheck
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    networks:
      - fincheck_network

volumes:
  pg_data:


networks:
  fincheck_network:
    driver: bridge
